[project]
name = "devto_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.10.4",
    "requests>=2.32.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "ruff>=0.7.2",
  {include-group = "test"},
  "mypy>=1.14.1",
  "isort>=5.13.2",
  "types-requests>=2.32.0.20241016",
]
test = [
  "pytest-cov>=6.0.0",
  "pytest>=8.3.3",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true
