name: "CICD"
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Develop shell
      uses: nicknovitski/nix-develop@v1
      with:
        arguments: --no-pure-eval
    # - name: Sync shell
    #   run: uv sync
    - name: Run tests
      run: pytest
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Develop shell
      uses: nicknovitski/nix-develop@v1
      with:
        arguments: --no-pure-eval
    # - name: Sync shell
    #   run: uv sync
    - name: Run linting
      run: ruff check
